# Generated by Django 5.1.7 on 2025-04-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='max_clients',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.timeslot'),
        ),
    ]
