# Generated by Django 5.1.6 on 2025-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('buy', 'Buy Property'), ('sell', 'Sell Property'), ('manage', 'Manage Property')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
